### PR TITLE
[M1192] handle ingest unicode encoding errors

### PR DESCRIPTION
**Pull request by saanobhaai**
## Summary by CodeRabbit

- **New Features**
	- Introduced enhanced error handling for character encoding issues in uploaded CSV files, providing detailed error messages for users.

- **Bug Fixes**
	- Improved response status codes for various error conditions during file ingestion, ensuring clearer communication of issues to users.

### CODE REVIEW

**Comment by saanobhaai** [comment]
[UnicodeDecodeError](https://trello.com/c/nEAOh6OS/1192-unicodedecodeerror)

**Comment by saanobhaai** [comment]
@coderabbitai review

**Comment by saanobhaai** [comment]
@coderabbitai review

**Review by gridcell — APPROVED** [review]

**Comment by saanobhaai** [comment]
[support invalid CR querying workflow](https://trello.com/c/UO75jmfp/1170-support-invalid-cr-querying-workflow)

**Pull request merged**
