### PR TITLE
Changes to maintain Legacy resources in Prod environment.

### PR DESCRIPTION
**Pull request by michaelconnor00**
These changes will allow for the dev branch to be merged into master without risk for the IaC moving the prod resources to the new EC2 cluster. 

## Summary by CodeRabbit

- **New Features**
  - Introduced `LegacyApiStack` for deploying legacy APIs.
  - Added support for image processing with new configuration settings.

- **Enhancements**
  - Updated AWS CDK version for improved infrastructure management.
  - Reorganized import statements across various settings files for better maintainability.

- **Refactor**
  - Adjusted task definitions and scheduling in API stack.
  - Enhanced queue operations and bucket access permissions.

- **Documentation**
  - Updated environment variable documentation to include `SYS_EMAIL`.

- **Bug Fixes**
  - Corrected import paths in development and production settings files.

### CODE REVIEW

**Comment by saanobhaai** [comment]
@coderabbitai review

**Comment by saanobhaai** [comment]
@coderabbitai review

**Comment by saanobhaai** [comment]
@coderabbitai review

**Comment by michaelconnor00** [comment]
I am closing this as Prod workers have already been changed to use the EC2 cluster, so these changes are no longer required.

**Pull request closed without merging**
